# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import asr_pb2 as asr__pb2


class ASRStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.workerSpeechToText = channel.stream_stream(
                '/zalotest.asr.ASR/workerSpeechToText',
                request_serializer=asr__pb2.VoiceRequest.SerializeToString,
                response_deserializer=asr__pb2.TextReply.FromString,
                )


class ASRServicer(object):
    """Missing associated documentation comment in .proto file."""

    def workerSpeechToText(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ASRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'workerSpeechToText': grpc.stream_stream_rpc_method_handler(
                    servicer.workerSpeechToText,
                    request_deserializer=asr__pb2.VoiceRequest.FromString,
                    response_serializer=asr__pb2.TextReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'zalotest.asr.ASR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ASR(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def workerSpeechToText(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/zalotest.asr.ASR/workerSpeechToText',
            asr__pb2.VoiceRequest.SerializeToString,
            asr__pb2.TextReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
