# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: asr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='asr.proto',
  package='zalotest.asr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tasr.proto\x12\x0czalotest.asr\"!\n\x0cVoiceRequest\x12\x11\n\tbyte_buff\x18\x01 \x01(\x0c\"+\n\x06Result\x12\r\n\x05\x66inal\x18\x01 \x01(\x08\x12\x12\n\ntranscript\x18\x02 \x01(\t\"Z\n\tTextReply\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03msg\x18\x02 \x01(\t\x12\n\n\x02id\x18\x03 \x01(\t\x12$\n\x06result\x18\x04 \x01(\x0b\x32\x14.zalotest.asr.Result2V\n\x03\x41SR\x12O\n\x12workerSpeechToText\x12\x1a.zalotest.asr.VoiceRequest\x1a\x17.zalotest.asr.TextReply\"\x00(\x01\x30\x01\x62\x06proto3'
)




_VOICEREQUEST = _descriptor.Descriptor(
  name='VoiceRequest',
  full_name='zalotest.asr.VoiceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='byte_buff', full_name='zalotest.asr.VoiceRequest.byte_buff', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=60,
)


_RESULT = _descriptor.Descriptor(
  name='Result',
  full_name='zalotest.asr.Result',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='final', full_name='zalotest.asr.Result.final', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transcript', full_name='zalotest.asr.Result.transcript', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=105,
)


_TEXTREPLY = _descriptor.Descriptor(
  name='TextReply',
  full_name='zalotest.asr.TextReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='zalotest.asr.TextReply.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='msg', full_name='zalotest.asr.TextReply.msg', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id', full_name='zalotest.asr.TextReply.id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='result', full_name='zalotest.asr.TextReply.result', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=197,
)

_TEXTREPLY.fields_by_name['result'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['VoiceRequest'] = _VOICEREQUEST
DESCRIPTOR.message_types_by_name['Result'] = _RESULT
DESCRIPTOR.message_types_by_name['TextReply'] = _TEXTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VoiceRequest = _reflection.GeneratedProtocolMessageType('VoiceRequest', (_message.Message,), {
  'DESCRIPTOR' : _VOICEREQUEST,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:zalotest.asr.VoiceRequest)
  })
_sym_db.RegisterMessage(VoiceRequest)

Result = _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
  'DESCRIPTOR' : _RESULT,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:zalotest.asr.Result)
  })
_sym_db.RegisterMessage(Result)

TextReply = _reflection.GeneratedProtocolMessageType('TextReply', (_message.Message,), {
  'DESCRIPTOR' : _TEXTREPLY,
  '__module__' : 'asr_pb2'
  # @@protoc_insertion_point(class_scope:zalotest.asr.TextReply)
  })
_sym_db.RegisterMessage(TextReply)



_ASR = _descriptor.ServiceDescriptor(
  name='ASR',
  full_name='zalotest.asr.ASR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=199,
  serialized_end=285,
  methods=[
  _descriptor.MethodDescriptor(
    name='workerSpeechToText',
    full_name='zalotest.asr.ASR.workerSpeechToText',
    index=0,
    containing_service=None,
    input_type=_VOICEREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ASR)

DESCRIPTOR.services_by_name['ASR'] = _ASR

# @@protoc_insertion_point(module_scope)
