# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sample.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sample.proto',
  package='SamplePackage',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csample.proto\x12\rSamplePackage\"F\n\x12\x45ntryCreateRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"a\n\rEntryResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x12\n\ncreated_on\x18\x06 \x01(\x05\x32k\n\rSampleService\x12Z\n\x11\x63reateBulkEntries\x12!.SamplePackage.EntryCreateRequest\x1a\x1c.SamplePackage.EntryResponse\"\x00(\x01\x30\x01\x62\x06proto3'
)




_ENTRYCREATEREQUEST = _descriptor.Descriptor(
  name='EntryCreateRequest',
  full_name='SamplePackage.EntryCreateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='SamplePackage.EntryCreateRequest.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='SamplePackage.EntryCreateRequest.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='SamplePackage.EntryCreateRequest.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=31,
  serialized_end=101,
)


_ENTRYRESPONSE = _descriptor.Descriptor(
  name='EntryResponse',
  full_name='SamplePackage.EntryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='SamplePackage.EntryResponse.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='title', full_name='SamplePackage.EntryResponse.title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='code', full_name='SamplePackage.EntryResponse.code', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='SamplePackage.EntryResponse.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='created_on', full_name='SamplePackage.EntryResponse.created_on', index=4,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=103,
  serialized_end=200,
)

DESCRIPTOR.message_types_by_name['EntryCreateRequest'] = _ENTRYCREATEREQUEST
DESCRIPTOR.message_types_by_name['EntryResponse'] = _ENTRYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EntryCreateRequest = _reflection.GeneratedProtocolMessageType('EntryCreateRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENTRYCREATEREQUEST,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:SamplePackage.EntryCreateRequest)
  })
_sym_db.RegisterMessage(EntryCreateRequest)

EntryResponse = _reflection.GeneratedProtocolMessageType('EntryResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENTRYRESPONSE,
  '__module__' : 'sample_pb2'
  # @@protoc_insertion_point(class_scope:SamplePackage.EntryResponse)
  })
_sym_db.RegisterMessage(EntryResponse)



_SAMPLESERVICE = _descriptor.ServiceDescriptor(
  name='SampleService',
  full_name='SamplePackage.SampleService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=202,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='createBulkEntries',
    full_name='SamplePackage.SampleService.createBulkEntries',
    index=0,
    containing_service=None,
    input_type=_ENTRYCREATEREQUEST,
    output_type=_ENTRYRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SAMPLESERVICE)

DESCRIPTOR.services_by_name['SampleService'] = _SAMPLESERVICE

# @@protoc_insertion_point(module_scope)
